//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefinitionExtractionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefinitionLink
    {
        public int ID { get; set; }
        public int Descriptor_ID { get; set; }
        public int Start_char { get; set; }
        public int Definition_ID { get; set; }
    
        public virtual Definition Definition { get; set; }
        public virtual Descriptor Descriptor { get; set; }
    }
}
