//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefinitionExtractionWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relation
    {
        public int ID { get; set; }
        public int Descriptor1_ID { get; set; }
        public int Descriptor2_ID { get; set; }
        public int Relation_type_ID { get; set; }
    
        public virtual Descriptor Descriptor { get; set; }
        public virtual Descriptor Descriptor1 { get; set; }
        public virtual Relation_types Relation_types { get; set; }
    }
}
